version: "3.9"
services:
  proxy:
    image: "ghcr.io/kumsil1006/oao-proxy:latest"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./ssl/certificate.crt:/etc/ssl/certificate.crt
      - ./ssl/private.key:/etc/ssl/private.key
  frontend:
    image: "ghcr.io/kumsil1006/oao-client:latest"
    restart: always
    expose:
      - "3000"
  backend:
    image: "ghcr.io/kumsil1006/oao-server:latest"
    restart: always
    expose:
      - "8080"
