name: 피처 요청 템플릿
description: 서비스에 필요한 새로운 피처 명세를 작성하고 개발자에게 요청하세요.
title: "request: "
labels: ["request"]
body: 
- type: input
  attributes: 
    label: 피처 개요
    description: 필요한 피처에 대해서 한줄로 설명해주세요.
  validations:
    required: true
- type: textarea
  attributes: 
    label: 요청 사유
    description: 해당 피처가 필요한 이유, 필요한 상황에 대해서 기술해주세요.
  validations:
    required: true
- type: dropdown
  attributes: 
    label: 중요도
    description: 해당 피처의 중요도를 선택해주세요.
    multiple: false
    options:
      - A
      - B
      - C
- type: dropdown
  attributes: 
    label: 난이도
    description: 해당 피처의 구현 난이도(구현 시간도 고려하여)을 선택해주세요.
    multiple: false
    options:
      - 상
      - 중
      - 하
  validations:
    required: true
- type: textarea
  attributes: 
    label: 피처 설명
    description: 필요한 피처에 대해서 자세히 설명해주세요.
  validations:
    required: false
- type: textarea
  attributes: 
    label: 체크리스트
    description: 작업에 필요한 마이크로 피처들을 작성해 이슈를 링크해주세요.
  validations:
    required: false
- type: input
  attributes: 
    label: 관련 정보
    description: 관련된 Project Wiki 페이지가 있다면 링크해주세요.
  validations:
    required: false
- type: checkboxes
  attributes: 
    label: 담당자 지정
    options:
      - label: assignee에 담당자를 제대로 지정하였나요?
        required: true
