name: dev-server CI/CD
on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  build-image:
    name: dev-server CI/CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node 설정
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Typescript 파일들 compile
        working-directory: "./server"
        env:
          CI: ""
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn build

      - name: GitHub Container Registry 로그인
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kumsil1006
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Docker images build 및 GitHub Container Registry로 push
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./server
          push: true
          tags: ghcr.io/kumsil1006/oao-dev-server

      - name: 실패시 슬랙 메시지 전송
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

      - name: 성공시 슬랙 메시지 전송
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: success
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
